version: '3.8'

services:
  rates-service:
    build:
      context: .
      dockerfile: API/FinancialPositions.RatesServices.API/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - CoinMarketCap__ApiKey=${COINMARKETCAP_API_KEY}
    networks:
      - microservices-network

  positions-service:
    build:
      context: .
      dockerfile: API/FinancialPositions.PositionsServices.API/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - microservices-network
    depends_on:
      - rates-service

networks:
  microservices-network:
    driver: bridge